language: java
deploy:
  on:
     branch: main
  skip_cleanup: true
  provider: heroku
  app: myapp-RazvanCopaceanu
  api_key:
    secure: VrXrUItE6cX3nOzwBCAq7LDRb3rTqkFFmjX2ym5MVRRiahIAXWVBILjmYRWqC/0zSFmkfJGEC+7kaFmAAaGUeOEml2IOJdfpL5DF1EdgCt0zZCe0kMP/EDXL0RBMzkG4K8D2sX9efP5R6NSpO3BfsV2qFr4dVZ0Aaj1KDhtoW7DydcQLQjbBGbW7h+4aXstulg+UTxawTDSGyGC6tyLMWt+Oef3b1mnt3aVXTGM2d4e/xDNB5fyPHunK8Mie7LzdN5tq7W9NUpk2gvrzn9EQ7wDXvqyV1oOAbBx16sH/VPIKjdYIRhGyDhaOBMXLxKEFQIWwoN/17dKf420tl2nN3RXrsQIWQirwnRpDIjobRtsZ711gy6haRen7Rj6Fgj212c8eYlpkovrlHbC1fQfCBPffbx/ITdEuXmE6EdZoU1TYTlQFCKdN73LhMwR/QaO2Wm/cZbVvMJlxw/OSvlnlh+QyO2CyIKbVdfaFb4cj8y1s79nfI7Wj2ASYZmnSaIlM4S6adyLnyWdYes0LwV5ASQtUga2dF2afpcnmefTVNomLbwtam7J5RsUlzFiXDrLmueLWtgf5IUWqZcr0Zbn1AFzM8Q2qYPVzGvxRrR8MLLak1zFfNPHscVK4oxfNO8mDLUjp1WlINeslRyqnNcCJOZPdeGVutJzY/3xBQo8jH2A=
